### ISSUE TITLE
Crash if IPv6 is not available

### ISSUE THREAD

**Issue by oxixes** [ckdo/airplay2-receiver#12]
My wifi adapter does not offer an IPv6, and the program crash on startup, I solved the issue by just commenting the IPv6 part on the code and removing it from sonos_one_setup, but I think it should be done better.

**Comment by Neustradamus** [comment]
@ All: If you have a bug, please create the issue in upstream :)
Same for a PR ;)

**Comment by oxixes** [comment]
I'll close this since this is resolved in openairplay/airplay2-receiver#31
